---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: "Include ansible-role-pulumi"
      include_role:
        name: "ansible-role-pulumi"
      vars:
        pulumi_version: "{{ lookup('env', 'pulumi_version') | default('latest', true) }}"
