---
- name: Verify
  hosts: all
  tasks:
  - name: Windows | Pulumi should be functionnal
    win_command: pulumi version
    register: pulumi_result

  - name: Windows | Verify commands outputs
    assert:
      that:
        - pulumi_result.rc == 0
      success_msg: "All tests passed"
